/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph
 */
public class ActualizarAuto extends javax.swing.JDialog {

    /**
     * Creates new form ActualizarAuto
     */
    public ActualizarAuto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        Atxt_Unidades = new javax.swing.JTextField();
        Atxt_Marca = new javax.swing.JTextField();
        Atxt_Modelo = new javax.swing.JTextField();
        Atxt_Costo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Atxt_Equipamiento = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Atxt_VIN = new javax.swing.JTextField();
        btn_Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NumUnidades:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        Atxt_Unidades.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(Atxt_Unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 140, -1));

        Atxt_Marca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(Atxt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 140, -1));

        Atxt_Modelo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(Atxt_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 140, -1));

        Atxt_Costo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(Atxt_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 140, -1));

        Atxt_Equipamiento.setColumns(20);
        Atxt_Equipamiento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Atxt_Equipamiento.setRows(5);
        jScrollPane1.setViewportView(Atxt_Equipamiento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 286, 166));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Equipamiento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Marca:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modelo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Costo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VIN:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 10, -1, -1));

        Atxt_VIN.setEditable(false);
        Atxt_VIN.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(Atxt_VIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 6, 74, -1));

        btn_Actualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_Actualizar.setText("Actualizar Registro");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        try {
            ConexionBD Con = new ConexionBD();
            Con.ConectarBD();
            String VIN =Atxt_VIN.getText();
            String Marca = Atxt_Marca.getText();
            String Modelo = Atxt_Modelo.getText();
            String CostoString = Atxt_Costo.getText();
            String UnidadesDString = Atxt_Unidades.getText();
            String Equipamiento = Atxt_Equipamiento.getText();
            double costo=Double.valueOf(CostoString);
            int ID=Integer.valueOf(VIN);
            int unidad=Integer.valueOf(UnidadesDString);
            String SQL ="CALL ActualizarAuto("+ID+",'"+Marca+"','"+Modelo+"','"+Equipamiento+"',"+costo+","+unidad+")";
            Con.sentencia.execute(SQL);
            JOptionPane.showMessageDialog(null, "Registro Actualizado");
            Con.DesconectarBD();
        }catch (SQLException ex) {
            Logger.getLogger(ActualizarAuto.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarAuto dialog = new ActualizarAuto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Atxt_Costo;
    public javax.swing.JTextArea Atxt_Equipamiento;
    public javax.swing.JTextField Atxt_Marca;
    public javax.swing.JTextField Atxt_Modelo;
    public javax.swing.JTextField Atxt_Unidades;
    public javax.swing.JTextField Atxt_VIN;
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
