/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionBD;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ricar
 */
public class Empleado_JF extends javax.swing.JFrame {

    /**
     * Creates new form Empleado_JF
     */
    public Empleado_JF() {
        initComponents();
         this.setLocationRelativeTo(null);
         Color fondo=new Color(158, 173, 192);
         this.getContentPane().setBackground(fondo);
         Crear_Modelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefono_txt = new javax.swing.JTextField();
        apellidos_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        contra_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        correo_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tipo_cbx = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        eliminar_btn = new javax.swing.JButton();
        guardar_btn = new javax.swing.JButton();
        limpiar_btn = new javax.swing.JButton();
        consultar_btn = new javax.swing.JButton();
        actualizar_btn = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Empleados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 40, 10));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        nombre_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 290, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teléfono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        telefono_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(telefono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 290, 30));

        apellidos_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(apellidos_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 290, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellidos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        contra_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(contra_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 290, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        correo_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(correo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 290, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        tipo_cbx.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tipo_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almacenista", "Administrador", "Chofer", "Guardia", "Limpieza", " " }));
        getContentPane().add(tipo_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 290, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Teléfono", "Contraseña", "Correo", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 570, 380));

        eliminar_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        eliminar_btn.setText("Eliminar");
        eliminar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        guardar_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        guardar_btn.setText("Guardar");
        guardar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(guardar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        limpiar_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        limpiar_btn.setText("Limpiar");
        limpiar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        consultar_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        consultar_btn.setText("Consultar");
        consultar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(consultar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        actualizar_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        actualizar_btn.setText("Actualizar");
        actualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        Salir.setBackground(new java.awt.Color(153, 0, 0));
        Salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, -1, -1));

        Regresar.setBackground(new java.awt.Color(153, 0, 0));
        Regresar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Regresar");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //  =============  FUNCIONA ===============
    private void guardar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_btnActionPerformed
        
         ConexionBD Con = new ConexionBD();
         Con.ConectarBD();
         
         String tipo = tipo_cbx.getSelectedItem().toString();
         String nombre = nombre_txt.getText();
         String apellidos = apellidos_txt.getText();
         String telefono = telefono_txt.getText();
         String correo = correo_txt.getText();
         String contrasenia = contra_txt.getText();
         
         if(!tipo.isEmpty()){
             if(!nombre.isEmpty()){
                 if(!apellidos.isEmpty()){
                     if(!telefono.isEmpty()){
                         if(!correo.isEmpty()){
                             if(!contrasenia.isEmpty()){
                                 
                                 try {
                                            String SQL = "CALL InsertarEmpleado('"+nombre+"','"+apellidos+"','"+telefono+"','"+contrasenia+"','"+correo+"','"+tipo+"');";
                                            Con.sentencia.execute(SQL);
                                            JOptionPane.showMessageDialog(null, "Los Datos fueron Insertados con exito");
                                            Consultar();
                                            nombre_txt.setText("");
                                            apellidos_txt.setText("");
                                            telefono_txt.setText("");
                                            correo_txt.setText("");
                                            contra_txt.setText("");
                                        } catch (SQLException ex) {
                                            Logger.getLogger(Empleado_JF.class.getName()).log(Level.SEVERE, null, ex);
                                        }                               
                             }else{
                                 JOptionPane.showMessageDialog(null, "Ingrese la contraseña");
                             }
                         }else{
                             JOptionPane.showMessageDialog(null, "Ingrese el correo");
                         }
                     }else{
                         JOptionPane.showMessageDialog(null, "Ingrese el teléfono");
                     }
                     
                 }else{
                     JOptionPane.showMessageDialog(null, "Ingrese los apellidos");
                 }
                 
             }else{
                 JOptionPane.showMessageDialog(null, "Ingrese el nombre");
             }
             
         }else{
             JOptionPane.showMessageDialog(null, "Ingrese el tipo");
         }
        
    }//GEN-LAST:event_guardar_btnActionPerformed
    
    
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleado_JF().setVisible(true);
            }
        });
    }
            DefaultTableModel modelo;
    
    
    
//  =============  Función para hacer consultas ===============
    
    private void Crear_Modelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        //================================ QUIZA SUELTE ERROR ===============
//                        "ID", "TD", "Documento", "Nombres", "Apellidos", "Telefono",
//                        "Direccion", "Fecha", "Hora", "Motivo"
                       "ID", "Nombre", "Apellidos", "Teléfono", "Contraseña", "Correo",
                        "Tipo"}) {
                Class[] types = new Class[]{
                    //Lo deje tal cual
                    java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class,
                    java.lang.String.class,java.lang.String.class,
                    java.lang.String.class,java.lang.String.class,
                    java.lang.String.class,java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    //Cambie esto
                    false, false, false, false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            table.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "Error");
        }

    }
    
    public void Consultar() {
        try {
            int i = 0;
            Object ob[] = null;
            ConexionBD Con = new ConexionBD();
            Con.ConectarBD();
            String SQL = "SELECT * FROM empleado";
            Con.resultado = Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()) {
                modelo.addRow(ob);
                modelo.setValueAt(Con.resultado.getString("id"), i, 0);
                modelo.setValueAt(Con.resultado.getString("nombre"), i, 1);
                modelo.setValueAt(Con.resultado.getString("apellidos"), i, 2);
                modelo.setValueAt(Con.resultado.getString("telefono"), i, 3);
                modelo.setValueAt(Con.resultado.getString("contraseña"), i, 4);
                modelo.setValueAt(Con.resultado.getString("correo"), i, 5);
                modelo.setValueAt(Con.resultado.getString("tipo"), i, 6);
                i++;
            }
            Con.DesconectarBD();

        } catch (SQLException ex) {
            Logger.getLogger(Empleado_JF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    private void consultar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_btnActionPerformed
        Consultar();
    }//GEN-LAST:event_consultar_btnActionPerformed

    private void eliminar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_btnActionPerformed
        try{
       String ID=table.getValueAt(table.getSelectedRow(),0).toString();
       ConexionBD Con=new ConexionBD();
       Con.ConectarBD();
       String SQL="DELETE FROM `empleado` WHERE id='"+ID+"'";
       Con.sentencia.execute(SQL);
       JOptionPane.showMessageDialog(null,"El registro fue eliminado");

       Con.DesconectarBD();
      }catch(SQLException ex){
        Logger.getLogger(Empleado_JF.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_eliminar_btnActionPerformed

    private void limpiar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar_btnActionPerformed
        // TODO add your handling code here:
        nombre_txt.setText("");
        apellidos_txt.setText("");
        telefono_txt.setText("");
        correo_txt.setText("");
        contra_txt.setText("");
    }//GEN-LAST:event_limpiar_btnActionPerformed

    private void actualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_btnActionPerformed
       
        
        String id = table.getValueAt(table.getSelectedRow(), 0).toString();
        String nombre = table.getValueAt(table.getSelectedRow(), 1).toString();
        String apellidos = table.getValueAt(table.getSelectedRow(), 2).toString();
        String telefono = table.getValueAt(table.getSelectedRow(), 3).toString();
        String correo = table.getValueAt(table.getSelectedRow(), 4).toString();
        String contrasenia = table.getValueAt(table.getSelectedRow(), 5).toString();
        String tipo = table.getValueAt(table.getSelectedRow(), 6).toString();

        Actualizar2 Act = new Actualizar2(null, true);
        Act.id_actua.setText(id);
        Act.nombre_actua.setText(nombre);
        Act.apellidos_actua.setText(apellidos);
        Act.telefono_actua.setText(telefono);
        Act.correo_actua.setText(correo);
        Act.contra_actua.setText(contrasenia);
        Act.tipo_actua.setSelectedItem(tipo);
        Act.setVisible(true);
        
        
        
    }//GEN-LAST:event_actualizar_btnActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        MenuADM adm=new MenuADM();
        adm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_RegresarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton actualizar_btn;
    private javax.swing.JTextField apellidos_txt;
    private javax.swing.JButton consultar_btn;
    private javax.swing.JTextField contra_txt;
    private javax.swing.JTextField correo_txt;
    private javax.swing.JButton eliminar_btn;
    private javax.swing.JButton guardar_btn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar_btn;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JTable table;
    private javax.swing.JTextField telefono_txt;
    private javax.swing.JComboBox<String> tipo_cbx;
    // End of variables declaration//GEN-END:variables
}
