/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Abraham
 */
public class Login extends javax.swing.JFrame {

   String usuario = NewUsuario.user1;
   String contraU = NewUsuario.pass1;
   String admin="Admin01";
   String contraA="12345678";
        
    public Login() {
        initComponents();
        Color fondo=new Color(158, 173, 192);
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        this.Fecha.setText(""+dtf.format(LocalDateTime.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        Fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        BTN_aqui = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Usuario.setCaretColor(new java.awt.Color(0, 0, 255));
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Usuario.setSelectionColor(new java.awt.Color(102, 255, 102));
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 215, 35));

        Ingresar.setBackground(new java.awt.Color(0, 51, 204));
        Ingresar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("Ingresar");
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        Salir.setBackground(new java.awt.Color(153, 0, 0));
        Salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordField1.setCaretColor(new java.awt.Color(0, 0, 255));
        jPasswordField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPasswordField1.setSelectionColor(new java.awt.Color(102, 255, 102));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 220, 35));

        Fecha.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("Hora");
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        Fecha1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Fecha1.setForeground(new java.awt.Color(255, 255, 255));
        Fecha1.setText("Si no tienes cuenta da click");
        getContentPane().add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        BTN_aqui.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BTN_aqui.setForeground(new java.awt.Color(0, 102, 153));
        BTN_aqui.setText("aquí");
        BTN_aqui.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_aqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_aquiMouseClicked(evt);
            }
        });
        getContentPane().add(BTN_aqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed

        String user = this.Usuario.getText();
        String pass = this.jPasswordField1.getText();
        int intentos = 1;

        if (user.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Introduce un usuario y contraseña", "No dejes en blanco", JOptionPane.ERROR_MESSAGE);
        }
        //Para usuario
        if (user.equals(usuario) || pass.equals(contraU)) {
            JOptionPane.showMessageDialog(null, "Bienvenido Usuario", "Acesso aceptado", JOptionPane.INFORMATION_MESSAGE);
            //MenuCLI cliente=new MenuCLI();
            //cliente.setVisible(true);
            this.dispose();
        }
        //Para Admin
        else if(user.equals(admin) || pass.equals(contraA)) {
            JOptionPane.showMessageDialog(null, "Bienvenido Administrador", "Acesso aceptado", JOptionPane.INFORMATION_MESSAGE);
            MenuADM adm=new MenuADM();
            adm.setVisible(true);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña invalidos", "Introduce de nuevo", JOptionPane.ERROR_MESSAGE);
            intentos = intentos + 1;

        }
        if (intentos == 3) {
            JOptionPane.showMessageDialog(null, "Bloqueo de Login", "Excediste el número de intentos", JOptionPane.ERROR_MESSAGE);
            this.Usuario.setEnabled(false);
            this.jPasswordField1.setEnabled(false);
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void BTN_aquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_aquiMouseClicked
        NewUsuario newU = new NewUsuario();
        newU.setVisible(true);
     
    }//GEN-LAST:event_BTN_aquiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTN_aqui;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
